spring.application.name=freshtrack-api
server.port=${PORT:8080}

# Database Configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.url=jdbc:postgresql://db.wbygolnlrcpcirdluzfv.supabase.co:5432/postgres?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=PLVRFTM7QPATl@
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.hikari.initialization-fail-timeout=60000
#spring.datasource.hikari.connection-timeout=30000
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=never

#Test
spring.datasource.url=jdbc:postgresql://db.wbygolnlrcpcirdluzfv.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=PLVRFTM7QPATl@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=my-super-secret-key-which-is-very-long
